/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AdminAddUser: typeof import('./src/components/admin/adminAddUser.vue')['default']
    AdminEditUserInfo: typeof import('./src/components/admin/adminEditUserInfo.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    CardInfo: typeof import('./src/components/page/home/cardInfo.vue')['default']
    CategoryBarBox: typeof import('./src/components/page/home/categoryBarBox.vue')['default']
    FooterLayout: typeof import('./src/components/layout/footerLayout.vue')['default']
    HomeBanner: typeof import('./src/components/page/home/homeBanner.vue')['default']
    HomeContentCard: typeof import('./src/components/page/home/homeContentCard.vue')['default']
    HomeTopContainer: typeof import('./src/components/page/home/homeTopContainer.vue')['default']
    NavLayout: typeof import('./src/components/layout/navLayout.vue')['default']
    NowTimeNews: typeof import('./src/components/page/home/nowTimeNews.vue')['default']
    Pagination: typeof import('./src/components/page/home/pagination.vue')['default']
    RightSideLayout: typeof import('./src/components/layout/rightSideLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideWrap: typeof import('./src/components/page/home/slideWrap.vue')['default']
    StickyLayout: typeof import('./src/components/page/home/stickyLayout.vue')['default']
    YmAvatar: typeof import('./src/components/ym/YmAvatar/YmAvatar.vue')['default']
    YmUploadImage: typeof import('./src/components/ym/YmUploadImage/YmUploadImage.vue')['default']
  }
}
