/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AdminAddUser: typeof import('./src/components/admin/adminAddUser.vue')['default']
    AdminEditUserInfo: typeof import('./src/components/admin/adminEditUserInfo.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    HomeOutlined: typeof import('@ant-design/icons-vue')['HomeOutlined']
    InboxOutlined: typeof import('@ant-design/icons-vue')['InboxOutlined']
    LoadingOutlined: typeof import('@ant-design/icons-vue')['LoadingOutlined']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmileOutlined: typeof import('@ant-design/icons-vue')['SmileOutlined']
    StepBackwardOutlined: typeof import('@ant-design/icons-vue')['StepBackwardOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    YmAvatar: typeof import('./src/components/ym/YmAvatar/YmAvatar.vue')['default']
    YmUploadImage: typeof import('./src/components/ym/YmUploadImage/YmUploadImage.vue')['default']
  }
}
